### PR TITLE
Changing connection pool refresh log level to info

### PR DESCRIPTION
**Pull request by roaet**
Maxim said it was warning for testing/rollout and can be downgraded to info

### CODE REVIEW

**Comment by roaet** [comment]
not sure if there is a release process for this library since the last one was in July.

**Comment by vtopc** [comment]
> not sure if there is a release process for this library since the last one was in July.

There is no. Just create a [release](https://github.com/mailgun/holster/releases) after merging, and update the upstream service.

**Comment by roaet** [comment]
right but medge had a PR merge in. i'll ask him

**Comment by roaet** [comment]
@MatthewEdge nbd if I cut a release with your PR. I imagine not, just checking.

**Pull request merged**
